//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvancedJustWareAPI.api.extra {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://newdawn.com/API", ConfigurationName="api.extra.IDataConversionService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IDataConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newdawn.com/API/IDataConversionService/DisableAutoGeneration", ReplyAction="http://newdawn.com/API/IDataConversionService/DisableAutoGenerationResponse")]
        void DisableAutoGeneration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newdawn.com/API/IDataConversionService/DisableAutoGeneration", ReplyAction="http://newdawn.com/API/IDataConversionService/DisableAutoGenerationResponse")]
        System.Threading.Tasks.Task DisableAutoGenerationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newdawn.com/API/IDataConversionService/EnableAutoGeneration", ReplyAction="http://newdawn.com/API/IDataConversionService/EnableAutoGenerationResponse")]
        void EnableAutoGeneration();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newdawn.com/API/IDataConversionService/EnableAutoGeneration", ReplyAction="http://newdawn.com/API/IDataConversionService/EnableAutoGenerationResponse")]
        System.Threading.Tasks.Task EnableAutoGenerationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newdawn.com/API/IDataConversionService/IsAutoGenerationEnabled", ReplyAction="http://newdawn.com/API/IDataConversionService/IsAutoGenerationEnabledResponse")]
        bool IsAutoGenerationEnabled();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://newdawn.com/API/IDataConversionService/IsAutoGenerationEnabled", ReplyAction="http://newdawn.com/API/IDataConversionService/IsAutoGenerationEnabledResponse")]
        System.Threading.Tasks.Task<bool> IsAutoGenerationEnabledAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://newdawn.com/API/IDataConversionService/TriggerAutoGeneration")]
        void TriggerAutoGeneration();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://newdawn.com/API/IDataConversionService/TriggerAutoGeneration")]
        System.Threading.Tasks.Task TriggerAutoGenerationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataConversionServiceChannel : AdvancedJustWareAPI.api.extra.IDataConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataConversionServiceClient : System.ServiceModel.ClientBase<AdvancedJustWareAPI.api.extra.IDataConversionService>, AdvancedJustWareAPI.api.extra.IDataConversionService {
        
        public DataConversionServiceClient() {
        }
        
        public DataConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DisableAutoGeneration() {
            base.Channel.DisableAutoGeneration();
        }
        
        public System.Threading.Tasks.Task DisableAutoGenerationAsync() {
            return base.Channel.DisableAutoGenerationAsync();
        }
        
        public void EnableAutoGeneration() {
            base.Channel.EnableAutoGeneration();
        }
        
        public System.Threading.Tasks.Task EnableAutoGenerationAsync() {
            return base.Channel.EnableAutoGenerationAsync();
        }
        
        public bool IsAutoGenerationEnabled() {
            return base.Channel.IsAutoGenerationEnabled();
        }
        
        public System.Threading.Tasks.Task<bool> IsAutoGenerationEnabledAsync() {
            return base.Channel.IsAutoGenerationEnabledAsync();
        }
        
        public void TriggerAutoGeneration() {
            base.Channel.TriggerAutoGeneration();
        }
        
        public System.Threading.Tasks.Task TriggerAutoGenerationAsync() {
            return base.Channel.TriggerAutoGenerationAsync();
        }
    }
}
